### ISSUE TITLE
Do you have the source for maple_loader.jar

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [bobc/maple-asp#1]
Hi Bob,

Sorry to bother you, but do you have the source for tools/win/maple_loader.jar ?

As I think I need to modify it to stop telling dfu-util to reset after upload, as this seems to intermittently cause errors on some systems.

Thanks

**Comment by bobc** [comment]
Sure, I didn't realise it wasn't there already.

**Comment by rogerclarkmelbourne** [comment]
Thanks bob

I've downloaded the new files and also NetBeans 8.x (as I didnt already have it - as I normally use Eclipse)

Cheers

Roger
